spring:
  config:
    activate:
      on-profile: docker

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.elibrary: INFO
    org.springframework: INFO
